### ISSUE TITLE
Loss does not decrease for a wavelength = 450 nm.

### ISSUE THREAD

**Issue by rongduo** [complight/realistic_defocus#4]
Thanks for opensourcing your awesome resources. 
When I tried to use the code to calculate a hologram after changing the wavelength to 450e-9 (0.000000450 in the configuration text file), the loss does not decrease and the reconstructed images are weird. Could you help me to figure this out?

**Comment by kaanaksit** [comment]
Copying @KorayKavakli to provide him with visibility.

**Comment by kaanaksit** [comment]
@rongduo Would you please change the `zero mode distance` to `0.35` when using `450 nm`? Please let me know if it works this way.

**Comment by rongduo** [comment]
@kaanaksit  Thanks a lot for your help, it works!
